### ISSUE TITLE
instructor-notes compulsory?

### ISSUE THREAD

**Issue by Athanasiamo** [carpentries/workbench#16]
I really love the workbench, its an excellent piece of work, and looks so much nicer and more contemporary. 
I find it generally easier to generate, serve locally and work with.

As i'm working on creating a new incubator lesson, I have some questions as I'm creating them, that I cant seem to find the answers to in the docs. Sorry if the questions belong to the docs repo in stead. Transfer if need be.

1. is the `instructors/instructor-notes.md` file mandatory? 
I'm getting build errors if I remove it (or name it something else), but can also not see where its rendered in the final site. 

```
Error in normalizePath(path, winslash = "/", mustWork = TRUE) : 
  path[1]="/Users/athanasm/workspace/conferences_workshops/swc/r-tidyverse-4-datasets/instructors/instructor-notes.md": No such file or directory
```

2. My lesson has some general instructions on how to "read" code, that I'd love to create a glossary for for the instructors. But creating an `instructors/glossary.md` file wont appear in the served site. not as I can see.

So, a follow-up to these two first questions:
3. Are files in the `instructor/` folder supposed to follow the same naming convention as in episodes to show up in the instructors view of the site? And is there a system for creating other instructors notes not necessarily tied directly to episodes, but rather to general content?
- I just saw that instructors notes can be added as asides  carpentries/sandpaper#26 , which is lovely! I just want to understand how that and the instructors folders work/complement each other

4. where is the glossary rendered? 
I've added a `glossary.md` to `instructors/` and `learners/` folders, but cant seem to understand where these should be rendered on the site.

** EDIT **
- ok, I just realised where the learner glossary and instructor-notes.md are rendered, but I found it a little hidden.
- is there a way to make the top nav more visible? I just actually didn't notice it was there. 
- and perhaps add a single line beneath the nav section you are at, to make it clear where on the page you are?
- the expanding aside where the episode list is, is great, but also somewhat hidden in what it actually contains when not expanded. Perhaps renaming "Expand" to "Episodes" ?

**Comment by zkamvar** [comment]
And once again, I realise that I have been a terrible host. Thank you for your detailed feedback @Athanasiamo! I really appreciate you taking the time to highlight these areas for improvement

**Comment by Athanasiamo** [comment]
you've been a great host, no worries @zkamvar . Your answers are thorough and thoghtful, its all good :) 

I did realise something else about the nav too. So, when in wide browser, everything looks fine. When narrowed, the nav dissapears and a "hamburger" appears. Now, this is all as expected, imo. The unexpected is that the content ov the hamburger nav when expanded, is _not_ the nav links as in the nav for the wide view.

![Nav in wide browser](https://user-images.githubusercontent.com/14014329/175489640-ed266375-f8c8-439e-8318-09f28fa7aa83.png)

![Nav hamburger in narrower browser](https://user-images.githubusercontent.com/14014329/175489768-5def93e0-2f6d-48ad-89a8-b8cf7ffe929f.png)


![Nav hambuger expanded in narrower browser](https://user-images.githubusercontent.com/14014329/175489800-4eb71ec6-4987-4582-9944-cdacd15524df.png)

So, the hambuger expands into episode list, but the nav links that exist in the wide browser are no where to be found (at least I cant find them).
It looks like we'll need to have a thorough look into the nav creation. 
Having experience with creating Hugo Themes, I always find navs tricky, so I can see how this can be missed.

**Comment by zkamvar** [comment]
Indeed, navbars are tricky AF, and I've opened https://github.com/carpentries/sandpaper/issues/306 to help me track this thank you!

**Comment by Athanasiamo** [comment]
for my part, all my questions have been answered or moved into meaningful new issues. SO we can close this is you dont have a need for it.

**Comment by zkamvar** [comment]
Thank you for your feedback and attention to detail!
