### ISSUE TITLE
[Feature request] Ability to link to individual sections or blocks on a page

### ISSUE THREAD

**Issue by anenadic** [carpentries/workbench#28]
In the old lesson format, when one hover over a section or block title - a little anchor appears which enables user to copy a direct link to that section of the page as shown on images below:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/631719/181198055-a595f29d-d2f9-4f97-b5cd-cbd9f5182b58.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/631719/181198150-bd523992-2ed5-4f5a-8d21-3e19b4eb2ac2.png">

**Comment by zkamvar** [comment]
Thank you for bringing this up! You'll be happy to know that it's already on my radar and I'll update on that issue when I arrive at that point https://github.com/carpentries/sandpaper/issues/285

**Comment by zkamvar** [comment]
This has been fixed and is now available as of sandpaper version 0.9.1 and varnish 0.2.3
