### ISSUE TITLE
Error: Arguments imply differing number of rows

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries/workbench#29]
When building a website using this template, I get the following error message:
```
arguments imply differing number of rows: 842, 28
Section (div) tags for 02-preparing-data.md will not be labelledFALSE
── Validating Fenced Divs ──────────────────────────────────────────────────────
Error in data.frame(node = rep(seq_along(divs), lengths(divs)), div = unlist(divs,  : 
  arguments imply differing number of rows: 842, 28
Calls: <Anonymous> ... <Anonymous> -> label_div_tags -> make_div_pairs -> data.frame
In addition: Warning messages:
1: In lines[!fenced_divs] <- rep(get_linestart(nodes[!fenced_divs]),  :
  number of items to replace is not a multiple of replacement length
2: In lines[!fenced_divs] <- rep(get_linestart(nodes[!fenced_divs]),  :
  number of items to replace is not a multiple of replacement length
Execution halted
Error: Process completed with exit code 1.
```
See [github action logs](https://github.com/esciencecenter-digital-skills/lesson-machine-learning-intro/runs/8107730687?check_suite_focus=true)

[Here](https://github.com/esciencecenter-digital-skills/lesson-machine-learning-intro/blob/039b37ca678db3cb4318350a0bc4e7ee126230d4/episodes/02-preparing-data.md) is the file that I am trying to render. Locally it sometimes builds successfully, and sometimes I get the same error, I haven't figured out in which cases it is successful.

What could it be? And maybe it would be nice to add a more user-friendly error message.

**Comment by zkamvar** [comment]
I will close this because I assume it was fixed, but feel free to open if you feel otherwise.
