### ISSUE TITLE
add a link to review and/or DOI in the banner for Lab lessons 

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/workbench#67]
It would be nice to re-introduce the celebration of a lesson passing peer review that was displayed as a banner in styles:

![Screenshot of the top of the Carpentries Lab lesson: Metagenomics Workshop Overview](https://github.com/carpentries/workbench/assets/9694524/65eb7df9-4cf5-4844-a337-60fd7934b1d0)

In a Workbench lesson, I think this could be a message in the same space as the life cycle stage is currently displayed. I guess this means adding templating for this into sandpaper and maybe also defining styling in varnish, but I need a bit more time to explore before I can be certain.

@zkamvar if you and the other maintainers are happy with the suggestion feel free to assign this one to me.

**Comment by tobyhodges** [comment]
Ah, thanks for the breadcrumbs to old discussions that I had forgotten about altogether 😅  This is very helpful advice: I will begin working something up in the coming days.

**Comment by zkamvar** [comment]
To be fair, it took me a while to find the right issue
