### ISSUE TITLE
Error: versionSpec parameter is required

### ISSUE THREAD

**Issue by avallecam** [carpentries/workbench#75]
**The problem:**

I made a fork of the `git-novice` lesson, and in a [PR from a branch to main](https://github.com/epiverse-trace/git-rstudio-basics/pull/3), I'm getting an error in the `Build markdown source files if valid` Job.

**A reprex:**

I reproduced this with a minimal edit in my personal repo and got the same results:

- PR: https://github.com/avallecam/git-novice/pull/1 
- Job error: https://github.com/avallecam/git-novice/actions/runs/6670403350/job/18130191403?pr=1#step:4:19

```
Run r-lib/actions/setup-r@v2
  with:
    use-public-rspm: true
    install-r: false
    r-version: release
    Ncpus: 1
    remove-openmp-macos: true
    http-user-agent: default
    windows-path-include-rtools: true
    windows-path-include-mingw: true
    update-rtools: false
  env:
    GITHUB_PAT: ***
    RENV_PATHS_ROOT: ~/.local/share/renv/
    CHIVE: /home/runner/work/git-novice/git-novice/site/chive
    PR: /home/runner/work/git-novice/git-novice/site/pr
    MD: /home/runner/work/git-novice/git-novice/site/built
Error: Error: versionSpec parameter is required
```

**Comment by Bisaloo** [comment]
This is likely due to a global issue unrelated to the workbench: https://github.com/r-lib/actions/issues/772

Could you try re-triggering the workflow to see if this issue is still present please?

**Comment by avallecam** [comment]
Thank you for linking this with the appropriate repo! The issue is now solved.
