### ISSUE TITLE
Formatting problems in instructor training callouts

### ISSUE THREAD

**Issue by ndporter** [carpentries/workbench#81]
Callouts in Instructor Training are displaying in CAPS UNDERLINE for all text ([example](https://carpentries.github.io/instructor-training/04-expertise.html#expert-awareness-gap)). 

It is not hard-coded that way in the episode and the pattern does not seem to hold for other lessons (I checked Data Carpentry Image Processing and the Maintainer Onboarding).

**Comment by froggleston** [comment]
At first glance, this is due to the callout-inner div seeming to have extra CSS properties:

`<div class="section level3 callout-title callout-inner">`

This should be:

`<div class="callout-inner">`

I'm unsure why these extra classes are being pulled in. I'll do some digging.

**Comment by froggleston** [comment]
Ah, it looks like a carbon copy of this bug, which is still open: https://github.com/carpentries/workbench/issues/59

**Comment by ErinBecker** [comment]
Closed with https://github.com/carpentries/sandpaper/pull/574. Screenshot below confirms text of callouts is no longer all caps underline. Thanks @froggleston for the fix and @ndporter (and @brownsarahm for reporting in https://github.com/carpentries/varnish/issues/128).

<img width="1190" alt="Screenshot 2024-03-22 at 2 27 45 PM" src="https://github.com/carpentries/workbench/assets/19176319/80ea2d22-50ff-49bc-b103-a1d67e537df1">
