### ISSUE TITLE
Banner 'Beta pilot testers wanted'

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries/workbench#82]
In the old template there used to be a clear 'Beta pilot testers wanted' banner. Is something like this still available in the Carpentries Workbench?

I couldn't find it in the documentation or FAQ

**Comment by froggleston** [comment]
Hi @svenvanderburg - I believe you can set the `workbench-beta` config option to render a "beta phase" banner: https://carpentries.github.io/sandpaper/reference/set_config.html?q=banner#optional-keypairs-known-by-sandpaper

However, I'm not sure of the exact wording used in that banner. Could you give it a try and let me know if it meets your requirements?

**Comment by svenvanderburg** [comment]
Putting `workbench-beta: TRUE` as config option gives this:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/e09d4b01-d37c-4638-9862-d9ab92d1e94c">

This is not what I want. But we are happy with a clear callout box:
